run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - services/store/sqlstore/migrations/

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment

linters:
  disable-all: true
  presets:
    - format
    - unused
    - complexity
    - bugs
    - performance

  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - goerr113
    - goheader
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosimple
    - lll
    - misspell
    - nlreturn
    - nolintlint
    - stylecheck
    - unconvert
    - whitespace
    - wsl

