version: '2.4'
services:
  postgres:
    extends:
        file: docker-compose.common.yml
        service: postgres
    tmpfs: /var/lib/postgresql/data
    ports:
      - 44446:5432

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    depends_on:
      - postgres
    command: postgres:5432

