version: '2.4'
services:
  mysql:
    extends:
        file: docker-compose.common.yml
        service: mysql
    tmpfs: /var/lib/mysql
    ports:
      - 44445:3306

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    depends_on:
      - mysql
    command: mysql

