name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 EXCLUDE_ENTERPRISE: true

jobs:

  ci-ubuntu-server:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        db:
          - mysql
          - mariadb
          - postgres

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "focalboard"
    - id: "mattermostServer"
      uses: actions/checkout@v3
      continue-on-error: true
      with:
        repository: "mattermost/mattermost-server"
        fetch-depth: "20"
        path: "mattermost-server"
        ref: ${{ env.BRANCH_NAME }}
    - uses: actions/checkout@v3
      if: steps.mattermostServer.outcome == 'failure'
      with:
        repository: "mattermost/mattermost-server"
        fetch-depth: "20"
        path: "mattermost-server"
        ref : "master"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.5

    - name: "Test server: ${{matrix['db']}}"
      run: cd focalboard; make server-test-${{matrix['db']}}

  ci-ubuntu-webapp:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "focalboard"
    - id: "mattermostServer"
      uses: actions/checkout@v3
      continue-on-error: true
      with:
        repository: "mattermost/mattermost-server"
        fetch-depth: "20"
        path: "mattermost-server"
        ref: ${{ env.BRANCH_NAME }}
    - uses: actions/checkout@v3
      if: steps.mattermostServer.outcome == 'failure'
      with:
        repository: "mattermost/mattermost-server"
        fetch-depth: "20"
        path: "mattermost-server"
        ref : "master"
    - name: npm ci
      run: |
        cd focalboard/webapp && npm ci && cd -
        cd focalboard/mattermost-plugin/webapp && npm ci

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.5

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.1.0

    - name: Lint & test webapp
      run: cd focalboard; make webapp-ci
