name: golangci-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-golangci:
    name: setup
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

  golangci:
    name: lint
    runs-on: ubuntu-18.04
    needs: setup-golangci
    steps:
      - name: server-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          working-directory: server
          skip-go-installation: true
      - name: plugin-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          working-directory: mattermost-plugin
          skip-go-installation: true
