name: golangci-lint

on:
  push:
    branches: [ main, release-** ]
  pull_request:
    branches: [ main, release-** ]
  workflow_dispatch:

jobs:
  golangci:
    name: plugin
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - uses: actions/checkout@v3
        with:
          path: "focalboard"
      - uses: actions/checkout@v3
        with:
          repository: "mattermost/mattermost-server"
          path: "mattermost-server"
      - name: prepare branches for multi-product
        run: |
          cd mattermost-server
          existed_in_remote=$(git ls-remote --heads origin ${GITHUB_REF_NAME})
          if [[ -z ${existed_in_remote} ]]; then
              git checkout ${GITHUB_REF_NAME}
          else
              git checkout master
          fi
      - name: set up golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
      - name: lint
        run: |
          cd focalboard
          make server-lint
