name: Mattermost Deploy

on:
  workflow_dispatch:

jobs:
  mattermost-deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout Focalboard
      uses: actions/checkout@v3
      with:
        path: './focalboard'

    - name: Checkout Mattermost-server
      uses: actions/checkout@v3
      with:
        repository: mattermost/mattermost-server
        path: './mattermost-server'

    - name: Checkout Mattermost-webapp
      uses: actions/checkout@v3
      with:
        repository: mattermost/mattermost-webapp
        path: './mattermost-webapp'

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.1.0

    - name: npm ci focalboard/webapp
      run: cd focalboard/webapp; npm ci --no-optional

    - name: npm ci focalboard/mattermost-plugin
      run: cd focalboard/mattermost-plugin/webapp; npm ci --no-optional

    - name: Setup Mattermost
      run: cd focalboard; make mm-setup-local

    - name: Deploy plugin
      run: cd focalboard; make mm-deploy-local

    - name: Cypress Mattermost tests
      run: |
        cd focalboard/webapp
        npm run cypress-mm:run

    - name: Rename plugin file
      run: cd focalboard/mattermost-plugin/dist; mv focalboard-*.tar.gz mattermost-plugin-focalboard.tar.gz

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v3
      with:
        name: mattermost-plugin-focalboard.tar.gz
        path: ${{ github.workspace }}/focalboard/mattermost-plugin/dist/mattermost-plugin-focalboard.tar.gz

    - name: Upload Cypress output
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-output
        path: |
          ${{ github.workspace }}/focalboard/webapp/cypress/logs/
          ${{ github.workspace }}/focalboard/webapp/cypress/screenshots/
